name: CI/CD with Terraform

on:
  push:
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
          

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Run CodeBuild
        uses: aws-actions/aws-codebuild-run-build@v1
        with:
          project-name: my-codebuild-job
          disable-source-override: true
          buildspec-override: |
            version: 0.2
            phases:
              install:

                commands:
                  - cd cicd
                  - chmod +x install-terraform.sh apply-terraform.sh
                  - install-terraform.sh
              
              pre_build:
                commands:
                  - echo "Pre-build phase"
              build:
                commands:
                  - /apply-terraform.sh

              post_build:
                - echo "Post-build phase"

              artifacts:
                files:
                  - '**/*'

