name: CI/CD with Terraform

on:
  push:
    branches:
      - main


jobs:
  terraform:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert end of line characters
        run: |
          sudo yum update -y
          sudo yum install -y dos2unix
          dos2unix ./cicd/install-terraform.sh
          dos2unix ./cicd/apply-terraform.sh
      

      - name: Make scripts executable
        run: chmod +x cicd/install-terraform.sh cicd/apply-terraform.sh

      - name: Install Terraform
        run: ./cicd/install-terraform.sh

      - name: Apply Terraform
        run: ./cicd/apply-terraform.sh
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}

